### ISSUE TITLE
Does not work with EL 7

### ISSUE THREAD

**Issue by jamesooden** [ckhall/puppet-module-remi#2]
The problem is simple, and that is the module has an equals version dependency on 'epel'.   If it had a >= dependency (is that possible with puppet modules) it would work just fine, as the latest 1.0.2 version of epel supports EL7 and the remi modules works great when that version of the epel module is installed.

I would you a merge request, but the project link goes to the epel module sources and not the remi module.

**Comment by ffrank** [comment]
@jamesooden I think you can create a PR  regardless of the project link. Unless I'm missing something completely here.

**Comment by ckhall** [comment]
i think is has been take care of at this point with a PR i Just merged.
